<b style="font-size:20pt"><center>CENTRAL VISAYAS COVID-19 VACCINATION SUMMARY REPORT</center></b>
<b style="font-size:17pt"><center>Data via SMS from Implementing Units as of</center></b>
<b style="font-size:17pt"><center><p class="text-blue">{{ date('F d Y')  }}</p></center></b><br>


<div class="table-responsive">
    <table style="font-size: 8pt;" class="table" border="2">
        <thead>
        <tr style="background-color: #fbe4d5">
            <th><b style="font-size: 10pt">Province</b></th>
            <th colspan="5"><b style="font-size: 10pt"><center>Vaccine Allocation</center></b></th>
            <th colspan="1"><b style="font-size: 10pt"><center>Eligible Population (A4)</center></b></th>
            <th colspan="10"><b style="font-size: 10pt"><center>Vaccinated</center></b></th>
            <th colspan="5"><b style="font-size: 10pt"><center>1st dose % Coverage(Total 1st dose Vaccinated / Total Eligible A4)</center></b></th>
            <th colspan="5"><b style="font-size: 10pt"><center>2nd dose % Coverage(Total 1st dose Vaccinated / Total Eligible A4)</center></b></th>
            <th colspan="2"><b style="font-size: 10pt"><center>Total Refusal</center></b></th>
            <th colspan="2"><b style="font-size: 10pt"><center>Total Deferral</center></b></th>
            <th colspan="5"><b style="font-size: 10pt"><center>Wastage</center></b></th>
            <th colspan="5"><b style="font-size: 10pt"><center>1st dose Consumption Rate</center></b></th>
            <th colspan="5"><b style="font-size: 10pt"><center>2nd dose Consumption Rate</center></b></th>
        </tr>
        <tr style="background-color: #fbe4d5;">
            <td></td>
            <td>Sinovac</td>
            <td>Astra</td>
            <td>Sputnikv</td>
            <td>Pfizer</td>
            <td>Total</td>
            <td></td>
            <td>1st Dose Sinovac</td>
            <td>2nd Dose Sinovac</td>
            <td>1st Dose AZ</td>
            <td>2nd Dose AZ</td>
            <td>1st Dose Pfizer</td>
            <td>2nd Dose Pfizer</td>
            <td>1st Dose Sputnikv</td>
            <td>2nd Dose Sputnikv</td>
            <td>1st Dose Total</td>
            <td>2nd Dose Total</td>
            <td>Sinovac</td>
            <td>Astra</td>
            <td>Sputnikv</td>
            <td>Pfizer</td>
            <td>Total</td>
            <td>Sinovac</td>
            <td>Astra</td>
            <td>Sputnikv</td>
            <td>Pfizer</td>
            <td>Total</td>
            <td>1st Dose</td>
            <td>2nd Dose</td>
            <td>1st Dose</td>
            <td>2nd Dose</td>
            <td>Sinovac</td>
            <td>Astra</td>
            <td>Pfizer</td>
            <td>Sputnikv</td>
            <td>Total Wastage</td>
            <td>Sinovac</td>
            <td>AZ</td>
            <td>Pfizer</td>
            <td>Sputnikv</td>
            <td>Total</td>
            <td>Sinovac</td>
            <td>AZ</td>
            <td>Pfizer</td>
            <td>Sputnikv</td>
            <td>Total</td>
        </tr>
        <tr style="background-color: #e2efd9">
            <td>Region 7</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Bohol</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Cebu</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Negros Or.</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Siquijor</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Cebu City</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Lapu-lapu City</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Mandaue City</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        </thead>
    </table>
</div>
